### ISSUE TITLE
Error when rendering scss to css

### ISSUE THREAD

**Issue by JrIdeA** [ysmood/nobone#21]
error message: 
Unhandled rejection Error: unknownType: The compiler should produce a number, string, buffer or function

Probably because node-sass's api `.renderSync` return object , not compiled css string
https://github.com/ysmood/nobone/blob/master/lib/modules/rendererWidgets.coffee#L218

and nokit's api `.inspect ` already change to `.xinspect`
https://github.com/ysmood/nobone/blob/master/lib/modules/rendererWidgets.coffee#L388

**Comment by ysmood** [comment]
fixed

**Comment by JrIdeA** [comment]
still having problem:
Unhandled rejection Error: unknownType: The compiler should produce a number, string, buffer or function

I found `ret.css`(https://github.com/ysmood/nobone/blob/master/lib/modules/rendererWidgets.coffee#L229) constructor.name is `SlowBuffer`

**Comment by ysmood** [comment]
Could you please make a PR to help me fix this bug?
